### ISSUE TITLE
自定义的 loading 和 error 为什么必须是一个 hash 值？

### ISSUE THREAD

**Issue by rguanghui** [banricho/vue-img#4]
- 使用绝对路径会很常见
- 为什么要有 error 这个选项？提示图片加载失败了？这个用不着吧
- 占位符没有默认图片？

**Comment by banricho** [comment]
一方面是绝对路径和 hash 混用可能会导致理解混乱，所以统一了。
另一方面是绝对路径在 activities 的构建环境下，每次需要更改项目目录有点麻烦，统一成  hash 以后，可以直接复制粘贴之前的项目配置。
最重要的还是可以在 Crayfish 配置，虽然目前并没有这样的需求。

error 这个选项就是图片 onerror 之后的替代图，如果不设置的话，还是以 loading 展示（因为没有触发 onload，也没有添加 error）。也就几行代码，不设置也没关系。

占位符没有写默认图……默认配置是最干净的，需要什么自己设置就好

**Comment by rguanghui** [comment]
loading 用 hash 的方式，很难想象。
